#ifndef VPNBRIDGE_H
#define VPNBRIDGE_H

#include <QDBusConnection>
#include <QDBusPendingCallWatcher>
#include <QObject>
#include <QString>

#include "helper1_interface.h"  // auto-generated by qt_add_dbus_interface()

/// VpnBridge is a thin D-Bus client that controls the coder-desktop-helper
/// system service over com.coder.Desktop.Helper1.
///
/// All VPN operations (TUN creation, DNS, routing) now live in the privileged
/// Go helper.  This class only sends D-Bus method calls and listens to signals.
///
/// VpnBridge is exposed to QML as a context property ("vpnBridge") in main.cpp.
/// We do NOT use QML_ELEMENT/QML_SINGLETON because the singleton lifetime is
/// managed manually (stack-allocated in main()).
class VpnBridge : public QObject {
    Q_OBJECT

    Q_PROPERTY(QString state READ state NOTIFY stateChanged)
    Q_PROPERTY(bool isRunning READ isRunning NOTIFY stateChanged)

public:
    explicit VpnBridge(QObject* parent = nullptr);

    [[nodiscard]] QString state() const { return m_state; }
    [[nodiscard]] bool isRunning() const { return m_state == QStringLiteral("connected"); }

    Q_INVOKABLE void start(const QString& url, const QString& token);
    Q_INVOKABLE void stop();

signals:
    void stateChanged();
    void errorOccurred(const QString& message);
    void peerUpdated(const QString& workspace, const QString& agent, const QString& hostname,
                     int status, int lastPingMs, bool isP2P);

private slots:
    void onStateChanged(const QString& newState, const QString& errorMessage);
    void onPeerUpdated(const QString& workspace, const QString& agent, const QString& hostname,
                       int status, int lastPingMs, bool isP2P);
    void onLogMessage(int level, const QString& message);
    void onStartFinished(QDBusPendingCallWatcher* watcher);
    void onStopFinished(QDBusPendingCallWatcher* watcher);
    void onGetStatusFinished(QDBusPendingCallWatcher* watcher);

private:
    ComCoderDesktopHelper1Interface m_helper;  // auto-generated D-Bus proxy
    QString m_state{QStringLiteral("disconnected")};
};

#endif  // VPNBRIDGE_H
